apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-content-pvc
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: wordpress
  resources:
    requests:
      storage: 512Mi
